### NumPy Basics 


Learning basic of NumPy from [NumPy quickstart](https://numpy.org/devdocs/user/quickstart.html). 
The objects are homogeneous multidimensional array. NumPy’s array class is called  ***ndarray***. It is also known by the alias array. 

**ndarray.ndim**: the number of axes (dimension) of the array. \
**ndarray.shape**: the dimension of the array. \
**ndarray.size**: the total number of elements of the array. Equals to the product of elements of the shape. \
**ndarray.type**: describe the type of the elements in the array. \
**ndarray.itemsize**: the size in bytes of each elements in the array.
**ndarray.data**: the buffer containing the actual elements of the array.


In [2]:
# import the library
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape #get the dimension of the array

(3, 5)

In [5]:
a.ndim # get the number of axes of the array

2

In [6]:
a.itemsize

4

In [7]:
a.dtype.name

'int32'

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [11]:
type(b)

numpy.ndarray

In [12]:
b.shape

(3,)

In [13]:
b.ndim

1

In [14]:
b

array([1, 2, 3])

### Array Creation

In [15]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [16]:
c.dtype

dtype('int32')

In [17]:
d = np.array([1.2,3.5,5.1])
d.dtype

dtype('float64')

In [18]:
e = np.array([(1.5,2,3), (4,5,6)])
e

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [20]:
f = np.array([[1,2],[3,4]], dtype=complex)
f

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [21]:
# function zeros create an array full of zeros 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# function ones create an array full of ones
np.ones((2,3,4), dtype= np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [23]:
# empty function create an array of random number
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [24]:
# arange function can be work as analogous to the range function
np.arange(10,30,5)

array([10, 15, 20, 25])

In [25]:
np.arange(0,2,.3) # it also accepts the float

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

### Printing arrays

In [28]:
#1 d array
a= np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
# 2 d array
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [30]:
# 3d array
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
